### ISSUE TITLE
Villager stacked

### ISSUE THREAD

**Issue by LogGits** [Nathat23/StackMob-2#145]
**Describe the bug**
Despite this setting:
```yaml
# StackMob 3 created by antiPerson.
# Report issues that you have experienced in the discussion thread.
# If the comments have been removed, see the config-default.yml file!
# 
# The size of the area around an entity that should be checked for matching entities to stack with.
check-area:
  x: 7
  y: 4
  z: 7
tag:
  interval: 10
  format: '&e&l%size%x &6&l%type%'
  always-visible: false
  remove-at: 1
  show-player-nearby:
    enabled: true
    x: 8
    y: 3
    z: 8
task-delay: 100
autosave-delay: 120
stack-max: 20
big-priority: true
remove-chunk-unload: false
stack-reasons:
- null
stack-types:
- null
stack-worlds:
- world2
- world2_the_end
- world2_nether
no-stack-reasons:
- BREEDING
- BUILD_IRONGOLEM
- BUILD_SNOWMAN
- BUILD_WITHER
- CHUNK_GEN
- CURED
- DEFAULT
- DISPENSE_EGG
- EGG
- ENDER_PEARL
- INFECTION
- JOCKEY
- LIGHTNING
- MOUNT
- NATURAL
- NETHER_PORTAL
- OCELOT_BABY
- REINFORCEMENTS
- SHOULDER_ENTITY
- SILVERFISH_BLOCK
- SLIME_SPLIT
- SPAWNER_EGG
- TRAP
- VILLAGE_DEFENSE
- VILLAGE_INVASION
no-stack-types:
- VILLAGER
- PARROT
no-stack-worlds:
- builds
dont-stack-until: 2
compare:
  villager-profession: true
  sheep-wool-sheared: true
  sheep-wool-color: true
  slime-size: true
  horse-color: true
  llama-color: true
  parrot-color: true
  entity-age: true
  can-breed: true
check:
  tamed: true
  leashed: true
  is-miniature-pet: true
  is-citizens-npc: true
multiply:
  creeper-explosion: true
  chicken-eggs: true
  sheep-wool: false
  mooshroom-mushrooms: false
  small-slimes: true
  breed: false
divide-on:
  sheep-shear: true
  sheep-dye: true
  mooshroom-shear: true
  breed: true
  tame: true
  name: true
death-type-permission: false
increase-player-stats: true
kill-all:
  enabled: false
  reason-blacklist:
  - ''
  type-blacklist:
  - ''
kill-step:
  enabled: true
  reason-blacklist:
  - ''
  type-blacklist:
  - ''
  max-step: 5
kill-step-damage:
  enabled: false
  reason-blacklist:
  - ''
  type-blacklist:
  - ''
multiply-drops:
  enabled: true
  entity-limit: 50
  drops-blacklist:
  - ''
  drop-one-per:
  - EMERALD
  - NETHER_STAR
  - TOTEM
multiply-exp:
  enabled: true
  algorithm: NORMAL
  custom-multiplier: 1.0
multiply-damage-done: true
multiply-damage-received:
  enabled: true
  cause-blacklist:
  - ''
no-targeting:
  enabled: false
  types-blacklist:
  - PHANTOM
no-ai:
  enabled: false
  use-whitelist: false
  types-whitelist:
  - ''
fire-ticks:
  enabled: true
  blacklist:
  - ''
mcmmo:
  no-experience:
    enabled: true
    blacklist:
    - ''
mythicmobs:
  enabled: true
  blacklist:
  - ''
jobs-reborn:
  enabled: true
  blacklist:
  - ''
worldguard-support: true
storage:
  type: FLATFILE
  database:
    ip: ''
    port: 3306
    name: ''
    username: ''
    password: ''
convert-existing-entities: false
```
Villagers stacked. 
Paper build 456 1.13.2. Stackmob 3.1.1
