### ISSUE TITLE
Doesn't support MythicMob's VanillaMobs

### ISSUE THREAD

**Issue by TrademarkTM** [Nathat23/StackMob-2#31]
I made this config to test:
```
PIG:
  Drops:
  - SkeletonKingDrops
  Options:
    PreventOtherDrops: true
```

What happens is that the mobs is not respawned. The killed stacked mob simply does not spawn another one in place. It's configured to kill mobs 1 by 1*

Actually, it have this error: https://hastebin.com/eninavagoc.vbs

Hope this can be fixed!
Thanks!
